version: 2.1

orbs:
  github-release: izumin5210/github-release@0.1.1
  heroku:         circleci/heroku@volatile
  slack:          circleci/slack@3

executors:
  golang:
    docker:
      - image: cimg/go:1.18
    environment:
      GO111MODULE: "on"

commands:
  with_cache:
    parameters:
      steps:
        type: steps
      cache_version:
        type: string
        default: "v2"

    steps:
      - restore_cache:
          keys:
            - << parameters.cache_version >>-go-mod-cache-{{ .Branch }}-{{ checksum "go.sum" }}
            - << parameters.cache_version >>-go-mod-cache-{{ .Branch }}-
            - << parameters.cache_version >>-go-mod-cache-

      - steps: << parameters.steps >>

      - save_cache:
          key: << parameters.cache_version >>-go-mod-cache-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

jobs:
  test:
    executor: golang

    steps:
      - checkout
      - with_cache:
          steps:
            - run: make test
            - run: make testrace
      - slack/notify-on-failure

  golint:
    executor: golang

    steps:
      - checkout
      - with_cache:
          steps:
            - run: go install golang.org/x/lint/golint@latest
            - run: make lint
      - slack/notify-on-failure

  go-vet:
    executor: golang

    steps:
      - checkout
      - with_cache:
          steps:
            - run: make vet
      - slack/notify-on-failure

  gofmt:
    executor: golang

    steps:
      - checkout
      - with_cache:
          steps:
            - run: "! gofmt -d . | grep '^'"
      - slack/notify-on-failure

  gox:
    executor: golang

    steps:
      - checkout
      - run: go get -u github.com/mitchellh/gox
      - run: rm bin/.keep
      - run: make gox_with_zip
      - persist_to_workspace:
          root: .
          paths:
            - .
      - slack/notify-on-failure

workflows:
  build-and-deploy:
    jobs:
      - test
      - golint
      - go-vet
      - gofmt

      - heroku/deploy-via-git:
          context: Heroku
          requires:
            - test
            - golint
            - go-vet
            - gofmt
          filters:
            branches:
              only: go_1.18
          post-deploy:
            - slack/status

  release:
    jobs:
      - gox:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(\.[a-z]+[0-9]*)?$/

      - github-release/create:
          executor: golang
          path: ./bin/
          prerelease: false
          requires:
            - gox
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/

      - github-release/create:
          executor: golang
          path: ./bin/
          prerelease: true
          requires:
            - gox
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+\.[a-z]+[0-9]*$/
