version: 2.1

orbs:
  github-release: izumin5210/github-release@0.1.1
  go-module:      timakin/go-module@0.3.0
  heroku:         circleci/heroku@volatile
  slack:          circleci/slack@3

executors:
  golang:
    docker:
      - image: cimg/go:1.16
    environment:
      GO111MODULE: "on"

jobs:
  test:
    executor: golang

    steps:
      - &attach_workspace
        attach_workspace:
          at: .
      - &restore_cache
        restore_cache:
          key: v2-go-mod-cache-{{ .Branch }}-{{ checksum "go.sum" }}
      - run: make test
      - run: make testrace
      - slack/notify-on-failure

  golint:
    executor: golang

    steps:
      - *attach_workspace
      - *restore_cache
      - run: go get -u golang.org/x/lint/golint
      - run: make lint
      - slack/notify-on-failure

  go-vet:
    executor: golang

    steps:
      - *attach_workspace
      - *restore_cache
      - run: make vet
      - slack/notify-on-failure

  gofmt:
    executor: golang

    steps:
      - *attach_workspace
      - *restore_cache
      - run: "! gofmt -d . | grep '^'"
      - slack/notify-on-failure

  gox:
    executor: golang

    steps:
      - checkout
      - run: go get -u github.com/mitchellh/gox
      - run: rm bin/.keep
      - run: make gox_with_zip
      - persist_to_workspace:
          root: .
          paths:
            - .
      - slack/notify-on-failure

workflows:
  build-and-deploy:
    jobs:
      - go-module/download:
          executor: golang
          persist-to-workspace: true

      - test:
          requires:
            - go-module/download

      - golint:
          requires:
            - go-module/download

      - go-vet:
          requires:
            - go-module/download

      - gofmt:
          requires:
            - go-module/download

      - heroku/deploy-via-git:
          context: Heroku
          requires:
            - test
            - golint
            - go-vet
            - gofmt
          filters:
            branches:
              only: master
          post-deploy:
            - slack/status

  release:
    jobs:
      - gox:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(\.[a-z]+[0-9]*)?$/

      - github-release/create:
          executor: golang
          path: ./bin/
          prerelease: false
          requires:
            - gox
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/

      - github-release/create:
          executor: golang
          path: ./bin/
          prerelease: true
          requires:
            - gox
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+\.[a-z]+[0-9]*$/
