version: 2.1

orbs:
  github-release: izumin5210/github-release@0.1.1
  slack:          circleci/slack@3

executors:
  golang:
    docker:
      - image: cimg/go:1.19
    environment:
      GO111MODULE: "on"

jobs:
  gox:
    executor: golang

    steps:
      - checkout
      - run: go install github.com/mitchellh/gox@latest
      - run: rm bin/.keep
      - run:
          command: make gox_with_zip
          no_output_timeout: 30m
      - persist_to_workspace:
          root: .
          paths:
            - .
      - slack/notify-on-failure

workflows:
  release:
    jobs:
      - gox:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(\.[a-z]+[0-9]*)?$/

      - github-release/create:
          executor: golang
          path: ./bin/
          prerelease: false
          requires:
            - gox
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/

      - github-release/create:
          executor: golang
          path: ./bin/
          prerelease: true
          requires:
            - gox
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+\.[a-z]+[0-9]*$/
