name: dependabot-auto-merge

on:
  pull_request_target:

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for Dependabot PRs
        if:
          contains(steps.dependabot-metadata.outputs.dependency-names, 'github.com/stretchr/testify') ||
          contains(steps.dependabot-metadata.outputs.dependency-names, 'github.com/jarcoal/httpmock') ||
          (
            steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor' &&
            (
              contains(steps.dependabot-metadata.outputs.dependency-names, 'github.com/aws/aws-lambda-go') ||
              contains(steps.dependabot-metadata.outputs.dependency-names, 'github.com/aws/aws-sdk-go') ||
              contains(steps.dependabot-metadata.outputs.dependency-names, 'github.com/xanzy/go-gitlab')
            )
          )
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Slack Notification (not success)
        uses: lazy-actions/slatify@master
        if: "! success()"
        continue-on-error: true
        with:
          job_name: '*auto-merge*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}
